# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl=https://localhost:44322/weatherforecast

GET {{baseUrl}}
Authorization: f,b

###

GET {{baseUrl}}
Authorization: b

###

GET {{baseUrl}}
Authorization: f